# Generated by Django 3.1.1 on 2021-03-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='classifier',
            field=models.IntegerField(null=True),
        ),
    ]
